# Generated by Django 5.2 on 2025-10-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_follow_following_follow_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watched_hidden',
            new_name='is_history_visible',
        ),
    ]
