# Generated by Django 5.2 on 2025-10-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_watched_hidden_user_is_history_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_history_visible',
            new_name='history_hidden',
        ),
    ]
