# Generated by Django 5.2 on 2025-12-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_is_history_visible_user_history_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='history_hidden',
            new_name='is_history_public',
        ),
    ]
