# Generated by Django 5.2 on 2026-03-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_history_hidden_user_is_history_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="folders",
        ),
    ]
