# Generated by Django 5.2 on 2026-03-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_follow_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
