# Generated by Django 5.2 on 2026-03-16 16:55

from django.db import migrations

import common.models.querysets


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", common.models.querysets.CustomUserManager()),
            ],
        ),
    ]
