# Generated by Django 5.2 on 2026-03-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_managers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
