# Generated by Django 5.2 on 2026-08-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_is_premium"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_history_public",
            new_name="is_hidden",
        ),
    ]
