# Generated by Django 5.2 on 2025-08-27 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_url', models.URLField(blank=True, null=True)),
                ('backdrop_local', models.ImageField(blank=True, null=True, upload_to='backdrops')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinopoisk_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(choices=[('actor', 'Актеры'), ('director', 'Режиссеры')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('medium', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('small', models.ImageField(blank=True, null=True, upload_to='posters')),
            ],
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('kp_rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('kp_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinopoisk_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('alternative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('SER', 'Сериал'), ('MOV', 'Фильм')], max_length=32, null=True)),
                ('age_rating', models.SmallIntegerField(blank=True, choices=[(0, '0+'), (12, '12+'), (16, '16+'), (18, '18+')], null=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, choices=[('SD', '480p'), ('HD', '720p'), ('FULL_HD', '1080p'), ('QUAD_HD', '2к'), ('UHD', '4к')], max_length=32, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('premiere', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleCreationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('limit', models.IntegerField(blank=True, default=1, null=True)),
                ('page', models.IntegerField(blank=True, default=1, null=True)),
                ('rating', models.CharField(blank=True, null=True)),
                ('is_series', models.BooleanField(blank=True, null=True)),
                ('year', models.CharField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, null=True)),
                ('sequels', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
