# Generated by Django 5.2 on 2025-08-27 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0003_initial'),
        ('titles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='title',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collections', to='lists.collection'),
        ),
        migrations.AddField(
            model_name='title',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='persons', to='titles.person'),
        ),
        migrations.AddField(
            model_name='title',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='studios', to='titles.studio'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='titles.title'),
        ),
        migrations.AddField(
            model_name='seasonsinfo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='titles.title'),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title'),
        ),
        migrations.AddField(
            model_name='poster',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='titles.title'),
        ),
        migrations.AddField(
            model_name='group',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_child', to='titles.title'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_parent', to='titles.title'),
        ),
        migrations.AddField(
            model_name='backdrop',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backdrops', to='titles.title'),
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title'),
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='title_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.seasonsinfo'),
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='seasonsinfo',
            unique_together={('title', 'episode', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('parent', 'child')},
        ),
        migrations.AlterUniqueTogether(
            name='backdrop',
            unique_together={('title', 'backdrop_url')},
        ),
    ]
