# Generated by Django 5.2 on 2025-09-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_group_child_alter_group_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='imdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='title',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
