# Generated by Django 5.2 on 2025-09-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_title_imdb_id_title_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
