# Generated by Django 5.2 on 2025-09-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_alter_title_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
