# Generated by Django 5.2 on 2025-09-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_alter_title_imdb_id_alter_title_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.URLField(blank=True, null=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='titles.seasonsinfo')),
                ('voiceover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='titles.voiceover')),
            ],
            options={
                'unique_together': {('voiceover', 'resource')},
            },
        ),
    ]
