# Generated by Django 5.2 on 2025-09-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_voiceover_videoresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoresource',
            old_name='resource',
            new_name='content_unit',
        ),
        migrations.AlterUniqueTogether(
            name='videoresource',
            unique_together={('voiceover', 'content_unit')},
        ),
    ]
