# Generated by Django 5.2 on 2025-09-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_rename_resource_videoresource_content_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewinghistory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='viewinghistory',
            name='title_content',
        ),
        migrations.RemoveField(
            model_name='viewinghistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='VideoResource',
        ),
        migrations.DeleteModel(
            name='VoiceOver',
        ),
        migrations.DeleteModel(
            name='ViewingHistory',
        ),
    ]
