# Generated by Django 5.2 on 2026-02-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0009_remove_viewinghistory_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="collections",
        ),
    ]
