# Generated by Django 5.2 on 2026-02-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0010_remove_title_collections"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TitleCreationHistory",
            new_name="TitleImportLog",
        ),
    ]
