# Generated by Django 5.2 on 2026-02-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0011_rename_titlecreationhistory_titleimportlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("series", "Сериал"), ("movie", "Фильм")],
                max_length=32,
                null=True,
            ),
        ),
    ]
