# Generated by Django 5.2 on 2026-03-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0012_alter_title_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
