# Generated by Django 5.2 on 2026-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0014_titlestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titlestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_watched", "Не смотрел"),
                    ("current", "Смотрю"),
                    ("planned", "В планах"),
                    ("watched", "Просмотрено"),
                    ("skipped", "Брошено"),
                ],
                default="not_watched",
                max_length=16,
            ),
        ),
    ]
