# Generated by Django 5.2 on 2026-08-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0015_alter_titlestatus_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RatingHistory",
        ),
    ]
