# Generated by Django 5.2 on 2026-08-23 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0016_delete_ratinghistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TitleStatus",
            new_name="LibraryEntry",
        ),
    ]
