# Generated by Django 5.2 on 2026-08-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0017_rename_titlestatus_libraryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryentry",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_entries",
                to="titles.title",
            ),
        ),
        migrations.AlterField(
            model_name="libraryentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
