# Generated by Django 5.2 on 2026-08-25 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0018_alter_libraryentry_title_alter_libraryentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
