# Generated by Django 5.2 on 2026-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0019_libraryentry_created_at_libraryentry_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libraryentry",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="libraryentry",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
