# Generated by Django 5.2 on 2026-08-29 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0020_remove_libraryentry_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
