# Generated by Django 5.2 on 2026-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0021_libraryentry_created_at_libraryentry_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="overview_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="overview_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="tagline_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="tagline_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
