# Generated by Django 5.2 on 2026-09-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0022_person_description_en_person_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="imdb_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
