# Generated by Django 5.2 on 2025-08-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='media',
            new_name='title',
        ),
    ]
