# Generated by Django 5.2 on 2025-09-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='like_count',
        ),
    ]
