# Generated by Django 5.2 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_rename_likes_comment_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="type",
            field=models.CharField(
                choices=[("feedback", "Отзыв"), ("review", "Рецензия")],
                default="feedback",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
