# Generated by Django 5.2 on 2026-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_comment_rating_comment_type_comment_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="type",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_review",
            field=models.BooleanField(default=False),
        ),
    ]
