# Generated by Django 5.2 on 2026-08-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0008_remove_comment_type_comment_is_review"),
        ("titles", "0020_remove_libraryentry_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_review",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="rating",
        ),
        migrations.AddField(
            model_name="comment",
            name="review",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entry",
                to="titles.libraryentry",
            ),
        ),
    ]
