# Generated by Django 5.2 on 2025-09-30 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titles', '0009_remove_viewinghistory_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title')),
                ('title_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.seasonsinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.URLField(blank=True, null=True)),
                ('content_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='titles.seasonsinfo')),
                ('voiceover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_player.voiceover')),
            ],
            options={
                'unique_together': {('voiceover', 'content_unit')},
            },
        ),
    ]
