# Generated by Django 5.2 on 2025-10-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewinghistory',
            name='title_content',
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video_player.videoresource'),
            preserve_default=False,
        ),
    ]
