# Generated by Django 5.2 on 2025-10-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_remove_viewinghistory_title_and_more'),
        ('video_player', '0002_remove_viewinghistory_title_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewinghistory',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='viewinghistory',
            name='title',
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videoresource',
            name='content_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='titles.seasonsinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoresource',
            name='iframe',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
