# Generated by Django 5.2 on 2025-10-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0003_remove_viewinghistory_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewinghistory',
            name='second',
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
