# Generated by Django 5.2 on 2025-10-27 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0004_remove_viewinghistory_second_viewinghistory_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewinghistory',
            unique_together={('user', 'resource')},
        ),
    ]
