# Generated by Django 5.2 on 2025-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0005_alter_viewinghistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinghistory',
            name='quality',
            field=models.CharField(choices=[('SD', '480p'), ('HD', '720p'), ('FULL_HD', '1080p'), ('QUAD_HD', '2k'), ('UHD', '4k')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
