# Generated by Django 5.2 on 2025-10-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0006_viewinghistory_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewinghistory',
            name='quality',
        ),
    ]
