# Generated by Django 5.2 on 2025-10-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0007_remove_viewinghistory_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinghistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
