# Generated by Django 5.2 on 2025-11-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0008_viewinghistory_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewinghistory',
            name='watched_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
