# Generated by Django 5.2 on 2026-03-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0013_title_updated_at"),
        ("video_player", "0009_alter_viewinghistory_watched_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket",
                        to="titles.title",
                    ),
                ),
            ],
        ),
    ]
