# Generated by Django 5.2 on 2026-03-12 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_player", "0010_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucket",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
