# Generated by Django 5.2 on 2026-09-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_player", "0011_alter_bucket_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceover",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="voiceover",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
