# Generated by Django 5.2 on 2025-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='type',
            field=models.CharField(choices=[('reset', 'Сброс пароля'), ('verification', 'Подтверждение учетной записи')], default=None, max_length=40),
        ),
    ]
