# Generated by Django 5.2 on 2025-09-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailverification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
