# Generated by Django 5.2 on 2026-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_emailverification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="type",
            field=models.CharField(
                choices=[
                    ("reset", "Сброс пароля"),
                    ("emai_verification", "Подтверждение учетной записи"),
                    ("registration", "Завершение регистрации"),
                ],
                default=None,
                max_length=40,
            ),
        ),
    ]
