# Generated by Django 5.2 on 2026-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_price_id",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
