# Generated by Django 5.2 on 2026-03-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_stripe_price_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
    ]
