# Generated by Django 5.2 on 2026-03-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_usersubscription_ends_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активная"),
                    ("past_due", "Просрочена"),
                    ("cancelled", "Отменена"),
                ],
                default="past_due",
                max_length=10,
            ),
        ),
    ]
