# Generated by Django 5.2 on 2026-03-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_alter_usersubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
