# Generated by Django 5.2 on 2025-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections')),
                ('type', models.CharField(blank=True, choices=[('SER_COL', 'Сериалы'), ('MOV_COL', 'Фильмы'), ('GEN', 'Жанры')], max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='folders')),
                ('cover', models.TextField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
