# Generated by Django 5.2 on 2025-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='medias', to='titles.title'),
        ),
    ]
