# Generated by Django 5.2 on 2025-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('SER_COL', 'Сериалы'), ('MOV_COL', 'Фильмы'), ('GEN', 'Жанры')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
