# Generated by Django 5.2 on 2025-08-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_collection_slug_alter_collection_type'),
        ('titles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='medias',
        ),
        migrations.AddField(
            model_name='folder',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='titles', to='titles.title'),
        ),
    ]
