# Generated by Django 5.2 on 2025-12-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(blank=True, choices=[('SER_COL', 'Сериалы'), ('MOV_COL', 'Фильмы'), ('GEN', 'Жанры')], max_length=32, null=True),
        ),
    ]
