# Generated by Django 5.2 on 2025-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('SER_COL', 'Сериалы'), ('MOV_COL', 'Фильмы'), ('GEN', 'Жанры')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
