# Generated by Django 5.2 on 2026-02-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0008_alter_collection_slug_alter_collection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="folder",
            name="type",
            field=models.CharField(
                choices=[("sys", "Системная"), ("def", "Обычная")],
                default="def",
                max_length=32,
            ),
        ),
    ]
