# Generated by Django 5.2 on 2026-02-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0009_folder_is_pinned_folder_type"),
        ("titles", "0010_remove_title_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="titles",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_titles", to="titles.title"
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="titles",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_titles", to="titles.title"
            ),
        ),
    ]
