# Generated by Django 5.2 on 2026-02-17 13:50

import django.core.validators
from django.db import migrations, models

import common.utils.files


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0011_alter_collection_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common.utils.files.upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
