# Generated by Django 5.2 on 2026-09-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0013_alter_folder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="name_en",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="name_ru",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
